% Generated by lilypond-book
% Options: [quote,noindent]

\version "2.2.4"
\header{
filename =      "test.ly"
title =         "Test"
composer =      "Herbert Brust"
enteredby =     "Burki"
copyright =     "Burki"
}

\include "deutsch.ly"

\paper {
    linewidth = 160 \mm - 2.0 * 9.0 \mm
    indent = 0.0\mm
}

#(set-global-staff-size 25)


melodie = \notes\relative c{
     \clef bass
     \key f \major
     \time 4/4
     a'2 g4 c,8. c16 | g'2 f4 a8. a16 |
     b4 a4 f4 a4 | g4 b8. a16 g4 c,8. c16 | c4 c4 g4 g4 |
     c2 c4 d8. d16 | b4 g4 c4 c4 | f4 e4 d4 c8. c16 | b2 f4 f'8. e16 |
     d2 a4 a'8. a16 | b4 g4 e8. f16 g4 | a2. d,8. d16 |  e4 es4 d4 es8. es16 |
     d4 c4 b4 h4 | c4 c4 c4 c4 | c2. c8. c16 |

     
}


\score {
   <<
    \new Staff { \melodie }
   >>
   \midi  { \tempo 4=96 }
  \paper {
    linewidth = 55 * \staffspace
  }
}
